---
title: "data_visualization_i"
author: "Mayuri Albal"
date: "2022-09-29"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

```

```{r}
library(tidyverse)
library (ggridges)
```
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_df
```
Making a Scatterplot
```{r}
ggplot (weather_df, aes (x =tmin, y= tmax))
```
Adding geometric point into the plot
```{r}
ggplot (weather_df, aes (x =tmin, y= tmax)) +geom_point ()
```
Same scatterplot but different
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r}
weather_df %>%
  drop_na %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

Lets make the same plot but different
```{r}
weather_scatterplot =
weather_df %>%
  drop_na () %>%
  ggplot(aes(x = tmin, y = tmax))

weather_scatterplot + geom_point ()
```

##Lets make fancier plots

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))+
  geom_smooth()
```

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))+
  geom_smooth (aes(color=name))
```


```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color= name)) + 
  geom_point(alpha = 0.3)+
  geom_smooth (se= FALSE)
```
Maybe make seperate plots
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color= name)) + 
  geom_point(alpha = 0.3)+
  geom_smooth (se= FALSE)+
  facet_grid(.~name)
```
'tmax' vs 'tmin' is boring, lets spice it up
```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax,color= name)) + 
    geom_point ()+ 
  geom_point(alpha = 0.3)+
  geom_smooth (se= FALSE)+
  facet_grid(.~name)
```
Percipitation coloring
```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax,color= prcp)) + 
    geom_point ()+ 
  geom_point(alpha = 0.3)+
  geom_smooth (se= FALSE)+
  facet_grid(.~name)
```
```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax,color= name)) + 
  geom_point(aes(size= prcp),alpha = 0.3)+
  geom_smooth (se= FALSE)+
  facet_grid(.~name)
```
Fix the axises
```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax,color= name)) + 
  geom_point(aes(size= prcp),alpha = 0.3)+
  geom_smooth (se= FALSE)+
  facet_grid(.~name)+
  theme (axis.text.x = element_text(angle =90, vjust =0.5, hjust= 1))
```

Some Quick Stuff
```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax_fahr = tmax * (9 / 5) + 32,
    tmin_fahr = tmin * (9 / 5) + 32) %>% 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point(alpha = .5) + 
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 
```
##Odds and Ends
```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 
```
