---
title: "EDA"
author: "Mayuri Albal"
date: "2022-10-06"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```



```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```
##Group-by
```{r}
weather_df %>%  
  group_by (name)
```
3 groups for names

```{r}
weather_df %>% 
  group_by (name, month)
```
36 groups for name and month

##Summarize

```{r}
weather_df %>% 
  group_by (name) %>% 
  summarize (
    n_obs = n()
  )
```
Provides 3 group summarizations


```{r}
weather_df %>% 
  group_by (name,month) %>% 
  summarize (
    n_obs = n()
  )
```


Can we count in other ways
```{r}
weather_df %>% 
count(name)
```
```{r}
weather_df %>% 
count(name,month)
```

Dont use 'table()'- Base R functions for making tables
```{r, eval= FALSE}
weather_df %>% 
  pull(month) %>% 
  table()
```

you can make multiple summaries
```{r}
weather_df %>% 
  group_by(month) %>% 
summarize(
  n_obs= n(),
  n_dist= n_distinct()
)
```
## a brief aside on 2x2 tables

```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name, cold) %>% 
  summarize(count = n())
```

```{r}
weather_df %>% 
  mutate(cold = case_when(
    tmax <  5 ~ "cold",
    tmax >= 5 ~ "not_cold",
    TRUE     ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name, cold)
```


##General Summaries

```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    mean_tmax = mean(tmax))
```

```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax)) %>% 
  view
```


```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE)) %>% 
  view
```
Removes the NA values from the analysis

```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    mean_tmax = mean(tmax),
    mean_prec = mean(prcp, na.rm = TRUE),
    median_tmax = median(tmax, na.rm= TRUE),
    sd_tmax = sd(tmax))
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(across(tmin:prcp, mean))
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>% 
  knitr::kable(digits = 1)
```


##Grouped Mutate

```{r}
weather_df %>%
  group_by(name) %>%
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point() 
```

